New upstream version 2.1.0

diff --git a/src/spacefm-auth b/src/spacefm-auth
--- a/src/spacefm-auth
+++ b/src/spacefm-auth
@@ -3,44 +3,49 @@
 # temporary scripts run as another user.  This file should not be modified
 # or run directly.
 
-if [ "$1" = "root" ]; then
+# License: See COPYING file
+
+set -euf -o pipefail
+
+
+if [ "${1-}" = "root" ];then
 	shift
 	fm_root=1
 else
 	fm_root=0
 fi
 
-if [ "$2" = "" ]; then
+if [ "${2-}" = "" ];then
 	echo "spacefm-auth: This script is used internally by spacefm and is not" 1>&2
 	echo "              designed to be run directly." 1>&2
 	exit 1
 fi
-	
-fm_source="$1"
-fm_sum="$2"
 
-if [ ! -f "$fm_source" ]; then
+fm_source="${1}"
+fm_sum="${2}"
+
+if [ ! -f "${fm_source}" ];then
 	echo "spacefm-auth: error: missing file"
 	exit 1
 fi
 
-if [ ${#fm_sum} -eq 64 ]; then
-	fm_sha=/usr/bin/sha256sum
-elif [ ${#fm_sum} -eq 128 ]; then
-	fm_sha=/usr/bin/sha512sum
+if [ ${#fm_sum} -eq 64 ];then
+	fm_hash=/usr/bin/xxh128sum
+elif [ ${#fm_sum} -eq 128 ];then
+	fm_hash=/usr/bin/xxh128sum
 else
 	echo "spacefm-auth: error: invalid sum" 1>&2
 	exit 1
 fi
 
-if (( fm_root == 1 )); then
+if (( fm_root == 1 ));then
 	chown root:root "$(dirname "$fm_source")" || exit 1
 	chmod ugo+rwx,+t "$(dirname "$fm_source")" || exit 1
 	chmod go-rwx "$fm_source" || exit 1
 fi
 
-if [ "$($fm_sha "$fm_source")" != "$fm_sum  $fm_source" ]; then
-	echo "spacefm-auth: error: $fm_sha mismatch" 1>&2
+if [ "$($fm_hash "$fm_source")" != "$fm_sum  $fm_source" ];then
+	echo "spacefm-auth: error: $fm_hash mismatch" 1>&2
 	exit 1
 fi
 
